=== prepare/icu4j/icu4j/tags/release-2-4-d01/src/com/ibm/icu/dev/tool/xmlcomparator/ResultXML.dtd
<!ELEMENT difference_xml (difference_element)* >

<!ELEMENT difference_element ( icu | ibm_toronto | windows | sun_jdk | ibm_jdk | solaris | apple | hp_ux | other)* >
<!ATTLIST difference_element parent_node NMTOKEN #IMPLIED >
<!ATTLIST difference_element node_name NMTOKEN #IMPLIED >
<!ATTLIST difference_element index NMTOKEN #IMPLIED >
<!ATTLIST difference_element id ID #REQUIRED >



<!ELEMENT icu (#PCDATA) >
<!ATTLIST icu case_diff NMTOKEN #IMPLIED >
<!ELEMENT ibm_toronto (#PCDATA) >
<!ATTLIST ibm_toronto case_diff NMTOKEN #IMPLIED >
<!ELEMENT windows (#PCDATA) >
<!ATTLIST windows case_diff NMTOKEN #IMPLIED >
<!ELEMENT sun_jdk (#PCDATA) >
<!ATTLIST sun_jdk case_diff NMTOKEN #IMPLIED >
<!ELEMENT ibm_jdk (#PCDATA) >
<!ATTLIST ibm_jdk case_diff NMTOKEN #IMPLIED >
<!ELEMENT solaris (#PCDATA) >
<!ATTLIST solaris case_diff NMTOKEN #IMPLIED >
<!ELEMENT apple (#PCDATA) >
<!ATTLIST apple case_diff NMTOKEN #IMPLIED >
<!ELEMENT hp_ux (#PCDATA) >
<!ATTLIST hp_ux case_diff NMTOKEN #IMPLIED >
<!ELEMENT other (#PCDATA) >
<!ATTLIST other case_diff NMTOKEN #IMPLIED >

=== prepare/icu4j/src/com/ibm/icu/dev/tool/xmlcomparator/ResultXML.xml
<!-- 
/**
 *******************************************************************************
 * Copyright (C) 2002-2002, International Business Machines Corporation and    *
 * others. All Rights Reserved.                                                *
 *******************************************************************************
 *
 * $Source: /xsrl/Nsvn/icu/icu4j/src/com/ibm/icu/dev/tool/xmlcomparator/Attic/ResultXML.xml,v $
 * $Date: 2002/12/18 03:56:41 $
 * $Revision: 1.2 $
 *
 *******************************************************************************
 */
-->
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE difference_xml SYSTEM "./ResultXML.dtd" >

<difference_xml>
    <difference_element parent_node="test" node_name="test" id="1" index="test">
        <icu case_diff="false" > </icu>
        <ibm_toronto case_diff="false"> </ibm_toronto>
        <windows case_diff="false"> </windows>
        <sun_jdk case_diff="false"> </sun_jdk>
        <ibm_jdk case_diff="false"> </ibm_jdk>
        <solaris case_diff="false"> </solaris>
        <apple case_diff="false"> </apple>
        <hp_ux case_diff="false"> </hp_ux>
        <other case_diff="false"> </other>
    </difference_element>
</difference_xml>
